//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasoma.Languages.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sasoma.Languages.Core.PropertyLabels", typeof(PropertyLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepts Reservations.
        /// </summary>
        internal static string acceptsReservations {
            get {
                return ResourceManager.GetString("acceptsReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountable Person.
        /// </summary>
        internal static string accountablePerson {
            get {
                return ResourceManager.GetString("accountablePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        internal static string actors {
            get {
                return ResourceManager.GetString("actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Name.
        /// </summary>
        internal static string additionalName {
            get {
                return ResourceManager.GetString("additionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Country.
        /// </summary>
        internal static string addressCountry {
            get {
                return ResourceManager.GetString("addressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Locality.
        /// </summary>
        internal static string addressLocality {
            get {
                return ResourceManager.GetString("addressLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Region.
        /// </summary>
        internal static string addressRegion {
            get {
                return ResourceManager.GetString("addressRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliation.
        /// </summary>
        internal static string affiliation {
            get {
                return ResourceManager.GetString("affiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Rating.
        /// </summary>
        internal static string aggregateRating {
            get {
                return ResourceManager.GetString("aggregateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        internal static string albums {
            get {
                return ResourceManager.GetString("albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Headline.
        /// </summary>
        internal static string alternativeHeadline {
            get {
                return ResourceManager.GetString("alternativeHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni.
        /// </summary>
        internal static string alumni {
            get {
                return ResourceManager.GetString("alumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni of.
        /// </summary>
        internal static string alumniOf {
            get {
                return ResourceManager.GetString("alumniOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Body.
        /// </summary>
        internal static string articleBody {
            get {
                return ResourceManager.GetString("articleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Section.
        /// </summary>
        internal static string articleSection {
            get {
                return ResourceManager.GetString("articleSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated Article.
        /// </summary>
        internal static string associatedArticle {
            get {
                return ResourceManager.GetString("associatedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated Media.
        /// </summary>
        internal static string associatedMedia {
            get {
                return ResourceManager.GetString("associatedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        internal static string attendees {
            get {
                return ResourceManager.GetString("attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        internal static string availability {
            get {
                return ResourceManager.GetString("availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        internal static string awards {
            get {
                return ResourceManager.GetString("awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Salary.
        /// </summary>
        internal static string baseSalary {
            get {
                return ResourceManager.GetString("baseSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        internal static string benefits {
            get {
                return ResourceManager.GetString("benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Rating.
        /// </summary>
        internal static string bestRating {
            get {
                return ResourceManager.GetString("bestRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string birthDate {
            get {
                return ResourceManager.GetString("birthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        internal static string bitrate {
            get {
                return ResourceManager.GetString("bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Posts.
        /// </summary>
        internal static string blogPosts {
            get {
                return ResourceManager.GetString("blogPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Edition.
        /// </summary>
        internal static string bookEdition {
            get {
                return ResourceManager.GetString("bookEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Format.
        /// </summary>
        internal static string bookFormat {
            get {
                return ResourceManager.GetString("bookFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string box {
            get {
                return ResourceManager.GetString("box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch of.
        /// </summary>
        internal static string branchOf {
            get {
                return ResourceManager.GetString("branchOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breadcrumb.
        /// </summary>
        internal static string breadcrumb {
            get {
                return ResourceManager.GetString("breadcrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Artist.
        /// </summary>
        internal static string byArtist {
            get {
                return ResourceManager.GetString("byArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string calories {
            get {
                return ResourceManager.GetString("calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string caption {
            get {
                return ResourceManager.GetString("caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbohydrate Content.
        /// </summary>
        internal static string carbohydrateContent {
            get {
                return ResourceManager.GetString("carbohydrateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string children {
            get {
                return ResourceManager.GetString("children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol Content.
        /// </summary>
        internal static string cholesterolContent {
            get {
                return ResourceManager.GetString("cholesterolContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string circle {
            get {
                return ResourceManager.GetString("circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleagues.
        /// </summary>
        internal static string colleagues {
            get {
                return ResourceManager.GetString("colleagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Text.
        /// </summary>
        internal static string commentText {
            get {
                return ResourceManager.GetString("commentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Time.
        /// </summary>
        internal static string commentTime {
            get {
                return ResourceManager.GetString("commentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Points.
        /// </summary>
        internal static string contactPoints {
            get {
                return ResourceManager.GetString("contactPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Type.
        /// </summary>
        internal static string contactType {
            get {
                return ResourceManager.GetString("contactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contained in.
        /// </summary>
        internal static string containedIn {
            get {
                return ResourceManager.GetString("containedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Location.
        /// </summary>
        internal static string contentLocation {
            get {
                return ResourceManager.GetString("contentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Rating.
        /// </summary>
        internal static string contentRating {
            get {
                return ResourceManager.GetString("contentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Size.
        /// </summary>
        internal static string contentSize {
            get {
                return ResourceManager.GetString("contentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content URL.
        /// </summary>
        internal static string contentURL {
            get {
                return ResourceManager.GetString("contentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor.
        /// </summary>
        internal static string contributor {
            get {
                return ResourceManager.GetString("contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooking Method.
        /// </summary>
        internal static string cookingMethod {
            get {
                return ResourceManager.GetString("cookingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook Time.
        /// </summary>
        internal static string cookTime {
            get {
                return ResourceManager.GetString("cookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Holder.
        /// </summary>
        internal static string copyrightHolder {
            get {
                return ResourceManager.GetString("copyrightHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Year.
        /// </summary>
        internal static string copyrightYear {
            get {
                return ResourceManager.GetString("copyrightYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string creator {
            get {
                return ResourceManager.GetString("creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies Accepted.
        /// </summary>
        internal static string currenciesAccepted {
            get {
                return ResourceManager.GetString("currenciesAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string dateCreated {
            get {
                return ResourceManager.GetString("dateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateline.
        /// </summary>
        internal static string dateline {
            get {
                return ResourceManager.GetString("dateline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string dateModified {
            get {
                return ResourceManager.GetString("dateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Posted.
        /// </summary>
        internal static string datePosted {
            get {
                return ResourceManager.GetString("datePosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Published.
        /// </summary>
        internal static string datePublished {
            get {
                return ResourceManager.GetString("datePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Date.
        /// </summary>
        internal static string deathDate {
            get {
                return ResourceManager.GetString("deathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string director {
            get {
                return ResourceManager.GetString("director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discusses.
        /// </summary>
        internal static string discusses {
            get {
                return ResourceManager.GetString("discusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion Url.
        /// </summary>
        internal static string discussionUrl {
            get {
                return ResourceManager.GetString("discussionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Requirements.
        /// </summary>
        internal static string educationRequirements {
            get {
                return ResourceManager.GetString("educationRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string elevation {
            get {
                return ResourceManager.GetString("elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed URL.
        /// </summary>
        internal static string embedURL {
            get {
                return ResourceManager.GetString("embedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Type.
        /// </summary>
        internal static string employmentType {
            get {
                return ResourceManager.GetString("employmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes Creative Work.
        /// </summary>
        internal static string encodesCreativeWork {
            get {
                return ResourceManager.GetString("encodesCreativeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding Format.
        /// </summary>
        internal static string encodingFormat {
            get {
                return ResourceManager.GetString("encodingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodings.
        /// </summary>
        internal static string encodings {
            get {
                return ResourceManager.GetString("encodings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode Number.
        /// </summary>
        internal static string episodeNumber {
            get {
                return ResourceManager.GetString("episodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        internal static string episodes {
            get {
                return ResourceManager.GetString("episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exif Data.
        /// </summary>
        internal static string exifData {
            get {
                return ResourceManager.GetString("exifData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Requirements.
        /// </summary>
        internal static string experienceRequirements {
            get {
                return ResourceManager.GetString("experienceRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        internal static string expires {
            get {
                return ResourceManager.GetString("expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        internal static string familyName {
            get {
                return ResourceManager.GetString("familyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat Content.
        /// </summary>
        internal static string fatContent {
            get {
                return ResourceManager.GetString("fatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        internal static string faxNumber {
            get {
                return ResourceManager.GetString("faxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber Content.
        /// </summary>
        internal static string fiberContent {
            get {
                return ResourceManager.GetString("fiberContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follows.
        /// </summary>
        internal static string follows {
            get {
                return ResourceManager.GetString("follows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founders.
        /// </summary>
        internal static string founders {
            get {
                return ResourceManager.GetString("founders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founding Date.
        /// </summary>
        internal static string foundingDate {
            get {
                return ResourceManager.GetString("foundingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string genre {
            get {
                return ResourceManager.GetString("genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo.
        /// </summary>
        internal static string geo {
            get {
                return ResourceManager.GetString("geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Name.
        /// </summary>
        internal static string givenName {
            get {
                return ResourceManager.GetString("givenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headline.
        /// </summary>
        internal static string headline {
            get {
                return ResourceManager.GetString("headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Price.
        /// </summary>
        internal static string highPrice {
            get {
                return ResourceManager.GetString("highPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiring Organization.
        /// </summary>
        internal static string hiringOrganization {
            get {
                return ResourceManager.GetString("hiringOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Location.
        /// </summary>
        internal static string homeLocation {
            get {
                return ResourceManager.GetString("homeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorific Prefix.
        /// </summary>
        internal static string honorificPrefix {
            get {
                return ResourceManager.GetString("honorificPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honorific Suffix.
        /// </summary>
        internal static string honorificSuffix {
            get {
                return ResourceManager.GetString("honorificSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrator.
        /// </summary>
        internal static string illustrator {
            get {
                return ResourceManager.GetString("illustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Album.
        /// </summary>
        internal static string inAlbum {
            get {
                return ResourceManager.GetString("inAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incentives.
        /// </summary>
        internal static string incentives {
            get {
                return ResourceManager.GetString("incentives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        internal static string industry {
            get {
                return ResourceManager.GetString("industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        internal static string ingredients {
            get {
                return ResourceManager.GetString("ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Language.
        /// </summary>
        internal static string inLanguage {
            get {
                return ResourceManager.GetString("inLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Playlist.
        /// </summary>
        internal static string inPlaylist {
            get {
                return ResourceManager.GetString("inPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Count.
        /// </summary>
        internal static string interactionCount {
            get {
                return ResourceManager.GetString("interactionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        internal static string isbn {
            get {
                return ResourceManager.GetString("isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Family Friendly.
        /// </summary>
        internal static string isFamilyFriendly {
            get {
                return ResourceManager.GetString("isFamilyFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Part of.
        /// </summary>
        internal static string isPartOf {
            get {
                return ResourceManager.GetString("isPartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Condition.
        /// </summary>
        internal static string itemCondition {
            get {
                return ResourceManager.GetString("itemCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List Element.
        /// </summary>
        internal static string itemListElement {
            get {
                return ResourceManager.GetString("itemListElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List Order.
        /// </summary>
        internal static string itemListOrder {
            get {
                return ResourceManager.GetString("itemListOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Offered.
        /// </summary>
        internal static string itemOffered {
            get {
                return ResourceManager.GetString("itemOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Reviewed.
        /// </summary>
        internal static string itemReviewed {
            get {
                return ResourceManager.GetString("itemReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Location.
        /// </summary>
        internal static string jobLocation {
            get {
                return ResourceManager.GetString("jobLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string jobTitle {
            get {
                return ResourceManager.GetString("jobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knows.
        /// </summary>
        internal static string knows {
            get {
                return ResourceManager.GetString("knows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Price.
        /// </summary>
        internal static string lowPrice {
            get {
                return ResourceManager.GetString("lowPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Content of Page.
        /// </summary>
        internal static string mainContentOfPage {
            get {
                return ResourceManager.GetString("mainContentOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string maps {
            get {
                return ResourceManager.GetString("maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of.
        /// </summary>
        internal static string memberOf {
            get {
                return ResourceManager.GetString("memberOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions.
        /// </summary>
        internal static string mentions {
            get {
                return ResourceManager.GetString("mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music by.
        /// </summary>
        internal static string musicBy {
            get {
                return ResourceManager.GetString("musicBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Group Member.
        /// </summary>
        internal static string musicGroupMember {
            get {
                return ResourceManager.GetString("musicGroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Episodes.
        /// </summary>
        internal static string numberOfEpisodes {
            get {
                return ResourceManager.GetString("numberOfEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pages.
        /// </summary>
        internal static string numberOfPages {
            get {
                return ResourceManager.GetString("numberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Tracks.
        /// </summary>
        internal static string numTracks {
            get {
                return ResourceManager.GetString("numTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition.
        /// </summary>
        internal static string nutrition {
            get {
                return ResourceManager.GetString("nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupational Category.
        /// </summary>
        internal static string occupationalCategory {
            get {
                return ResourceManager.GetString("occupationalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Count.
        /// </summary>
        internal static string offerCount {
            get {
                return ResourceManager.GetString("offerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        internal static string offers {
            get {
                return ResourceManager.GetString("offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        internal static string openingHours {
            get {
                return ResourceManager.GetString("openingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        internal static string parents {
            get {
                return ResourceManager.GetString("parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of Season.
        /// </summary>
        internal static string partOfSeason {
            get {
                return ResourceManager.GetString("partOfSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of TV Series.
        /// </summary>
        internal static string partOfTVSeries {
            get {
                return ResourceManager.GetString("partOfTVSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Accepted.
        /// </summary>
        internal static string paymentAccepted {
            get {
                return ResourceManager.GetString("paymentAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performer in.
        /// </summary>
        internal static string performerIn {
            get {
                return ResourceManager.GetString("performerIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performers.
        /// </summary>
        internal static string performers {
            get {
                return ResourceManager.GetString("performers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string photos {
            get {
                return ResourceManager.GetString("photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Type.
        /// </summary>
        internal static string playerType {
            get {
                return ResourceManager.GetString("playerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        internal static string polygon {
            get {
                return ResourceManager.GetString("polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Office Box Number.
        /// </summary>
        internal static string postOfficeBoxNumber {
            get {
                return ResourceManager.GetString("postOfficeBoxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prep Time.
        /// </summary>
        internal static string prepTime {
            get {
                return ResourceManager.GetString("prepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Currency.
        /// </summary>
        internal static string priceCurrency {
            get {
                return ResourceManager.GetString("priceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Range.
        /// </summary>
        internal static string priceRange {
            get {
                return ResourceManager.GetString("priceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Valid Until.
        /// </summary>
        internal static string priceValidUntil {
            get {
                return ResourceManager.GetString("priceValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Image of Page.
        /// </summary>
        internal static string primaryImageOfPage {
            get {
                return ResourceManager.GetString("primaryImageOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Column.
        /// </summary>
        internal static string printColumn {
            get {
                return ResourceManager.GetString("printColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Edition.
        /// </summary>
        internal static string printEdition {
            get {
                return ResourceManager.GetString("printEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Page.
        /// </summary>
        internal static string printPage {
            get {
                return ResourceManager.GetString("printPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Section.
        /// </summary>
        internal static string printSection {
            get {
                return ResourceManager.GetString("printSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        internal static string producer {
            get {
                return ResourceManager.GetString("producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string productID {
            get {
                return ResourceManager.GetString("productID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Company.
        /// </summary>
        internal static string productionCompany {
            get {
                return ResourceManager.GetString("productionCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein Content.
        /// </summary>
        internal static string proteinContent {
            get {
                return ResourceManager.GetString("proteinContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        internal static string provider {
            get {
                return ResourceManager.GetString("provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string publisher {
            get {
                return ResourceManager.GetString("publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Principles.
        /// </summary>
        internal static string publishingPrinciples {
            get {
                return ResourceManager.GetString("publishingPrinciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        internal static string qualifications {
            get {
                return ResourceManager.GetString("qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Count.
        /// </summary>
        internal static string ratingCount {
            get {
                return ResourceManager.GetString("ratingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Value.
        /// </summary>
        internal static string ratingValue {
            get {
                return ResourceManager.GetString("ratingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Category.
        /// </summary>
        internal static string recipeCategory {
            get {
                return ResourceManager.GetString("recipeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Cuisine.
        /// </summary>
        internal static string recipeCuisine {
            get {
                return ResourceManager.GetString("recipeCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Instructions.
        /// </summary>
        internal static string recipeInstructions {
            get {
                return ResourceManager.GetString("recipeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Yield.
        /// </summary>
        internal static string recipeYield {
            get {
                return ResourceManager.GetString("recipeYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions Allowed.
        /// </summary>
        internal static string regionsAllowed {
            get {
                return ResourceManager.GetString("regionsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related to.
        /// </summary>
        internal static string relatedTo {
            get {
                return ResourceManager.GetString("relatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to Url.
        /// </summary>
        internal static string replyToUrl {
            get {
                return ResourceManager.GetString("replyToUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative of Page.
        /// </summary>
        internal static string representativeOfPage {
            get {
                return ResourceManager.GetString("representativeOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Subscription.
        /// </summary>
        internal static string requiresSubscription {
            get {
                return ResourceManager.GetString("requiresSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibilities.
        /// </summary>
        internal static string responsibilities {
            get {
                return ResourceManager.GetString("responsibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Body.
        /// </summary>
        internal static string reviewBody {
            get {
                return ResourceManager.GetString("reviewBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Count.
        /// </summary>
        internal static string reviewCount {
            get {
                return ResourceManager.GetString("reviewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Rating.
        /// </summary>
        internal static string reviewRating {
            get {
                return ResourceManager.GetString("reviewRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string reviews {
            get {
                return ResourceManager.GetString("reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Currency.
        /// </summary>
        internal static string salaryCurrency {
            get {
                return ResourceManager.GetString("salaryCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturated Fat Content.
        /// </summary>
        internal static string saturatedFatContent {
            get {
                return ResourceManager.GetString("saturatedFatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Number.
        /// </summary>
        internal static string seasonNumber {
            get {
                return ResourceManager.GetString("seasonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        internal static string seasons {
            get {
                return ResourceManager.GetString("seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        internal static string seller {
            get {
                return ResourceManager.GetString("seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serves Cuisine.
        /// </summary>
        internal static string servesCuisine {
            get {
                return ResourceManager.GetString("servesCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving Size.
        /// </summary>
        internal static string servingSize {
            get {
                return ResourceManager.GetString("servingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siblings.
        /// </summary>
        internal static string siblings {
            get {
                return ResourceManager.GetString("siblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant Links.
        /// </summary>
        internal static string significantLinks {
            get {
                return ResourceManager.GetString("significantLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium Content.
        /// </summary>
        internal static string sodiumContent {
            get {
                return ResourceManager.GetString("sodiumContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Organization.
        /// </summary>
        internal static string sourceOrganization {
            get {
                return ResourceManager.GetString("sourceOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Commitments.
        /// </summary>
        internal static string specialCommitments {
            get {
                return ResourceManager.GetString("specialCommitments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        internal static string spouse {
            get {
                return ResourceManager.GetString("spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        internal static string streetAddress {
            get {
                return ResourceManager.GetString("streetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Events.
        /// </summary>
        internal static string subEvents {
            get {
                return ResourceManager.GetString("subEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar Content.
        /// </summary>
        internal static string sugarContent {
            get {
                return ResourceManager.GetString("sugarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Event.
        /// </summary>
        internal static string superEvent {
            get {
                return ResourceManager.GetString("superEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string thumbnail {
            get {
                return ResourceManager.GetString("thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Url.
        /// </summary>
        internal static string thumbnailUrl {
            get {
                return ResourceManager.GetString("thumbnailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker Symbol.
        /// </summary>
        internal static string tickerSymbol {
            get {
                return ResourceManager.GetString("tickerSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string totalTime {
            get {
                return ResourceManager.GetString("totalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        internal static string tracks {
            get {
                return ResourceManager.GetString("tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        internal static string trailer {
            get {
                return ResourceManager.GetString("trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcript.
        /// </summary>
        internal static string transcript {
            get {
                return ResourceManager.GetString("transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Fat Content.
        /// </summary>
        internal static string transFatContent {
            get {
                return ResourceManager.GetString("transFatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaturated Fat Content.
        /// </summary>
        internal static string unsaturatedFatContent {
            get {
                return ResourceManager.GetString("unsaturatedFatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Date.
        /// </summary>
        internal static string uploadDate {
            get {
                return ResourceManager.GetString("uploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Frame Size.
        /// </summary>
        internal static string videoFrameSize {
            get {
                return ResourceManager.GetString("videoFrameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Quality.
        /// </summary>
        internal static string videoQuality {
            get {
                return ResourceManager.GetString("videoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Count.
        /// </summary>
        internal static string wordCount {
            get {
                return ResourceManager.GetString("wordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Hours.
        /// </summary>
        internal static string workHours {
            get {
                return ResourceManager.GetString("workHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Location.
        /// </summary>
        internal static string workLocation {
            get {
                return ResourceManager.GetString("workLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Works for.
        /// </summary>
        internal static string worksFor {
            get {
                return ResourceManager.GetString("worksFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst Rating.
        /// </summary>
        internal static string worstRating {
            get {
                return ResourceManager.GetString("worstRating", resourceCulture);
            }
        }
    }
}
