//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasoma.Languages.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TypeLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypeLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sasoma.Languages.Core.TypeLabels", typeof(TypeLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Page.
        /// </summary>
        internal static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting Service.
        /// </summary>
        internal static string AccountingService {
            get {
                return ResourceManager.GetString("AccountingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Area.
        /// </summary>
        internal static string AdministrativeArea {
            get {
                return ResourceManager.GetString("AdministrativeArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult Entertainment.
        /// </summary>
        internal static string AdultEntertainment {
            get {
                return ResourceManager.GetString("AdultEntertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Offer.
        /// </summary>
        internal static string AggregateOffer {
            get {
                return ResourceManager.GetString("AggregateOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate Rating.
        /// </summary>
        internal static string AggregateRating {
            get {
                return ResourceManager.GetString("AggregateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport.
        /// </summary>
        internal static string Airport {
            get {
                return ResourceManager.GetString("Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amusement Park.
        /// </summary>
        internal static string AmusementPark {
            get {
                return ResourceManager.GetString("AmusementPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Shelter.
        /// </summary>
        internal static string AnimalShelter {
            get {
                return ResourceManager.GetString("AnimalShelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment Complex.
        /// </summary>
        internal static string ApartmentComplex {
            get {
                return ResourceManager.GetString("ApartmentComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquarium.
        /// </summary>
        internal static string Aquarium {
            get {
                return ResourceManager.GetString("Aquarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Gallery.
        /// </summary>
        internal static string ArtGallery {
            get {
                return ResourceManager.GetString("ArtGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attorney.
        /// </summary>
        internal static string Attorney {
            get {
                return ResourceManager.GetString("Attorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Object.
        /// </summary>
        internal static string AudioObject {
            get {
                return ResourceManager.GetString("AudioObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Body Shop.
        /// </summary>
        internal static string AutoBodyShop {
            get {
                return ResourceManager.GetString("AutoBodyShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Dealer.
        /// </summary>
        internal static string AutoDealer {
            get {
                return ResourceManager.GetString("AutoDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Teller.
        /// </summary>
        internal static string AutomatedTeller {
            get {
                return ResourceManager.GetString("AutomatedTeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automotive Business.
        /// </summary>
        internal static string AutomotiveBusiness {
            get {
                return ResourceManager.GetString("AutomotiveBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Parts Store.
        /// </summary>
        internal static string AutoPartsStore {
            get {
                return ResourceManager.GetString("AutoPartsStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Rental.
        /// </summary>
        internal static string AutoRental {
            get {
                return ResourceManager.GetString("AutoRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Repair.
        /// </summary>
        internal static string AutoRepair {
            get {
                return ResourceManager.GetString("AutoRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Wash.
        /// </summary>
        internal static string AutoWash {
            get {
                return ResourceManager.GetString("AutoWash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakery.
        /// </summary>
        internal static string Bakery {
            get {
                return ResourceManager.GetString("Bakery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank or Credit Union.
        /// </summary>
        internal static string BankOrCreditUnion {
            get {
                return ResourceManager.GetString("BankOrCreditUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar or Pub.
        /// </summary>
        internal static string BarOrPub {
            get {
                return ResourceManager.GetString("BarOrPub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beach.
        /// </summary>
        internal static string Beach {
            get {
                return ResourceManager.GetString("Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty Salon.
        /// </summary>
        internal static string BeautySalon {
            get {
                return ResourceManager.GetString("BeautySalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed And Breakfast.
        /// </summary>
        internal static string BedAndBreakfast {
            get {
                return ResourceManager.GetString("BedAndBreakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike Store.
        /// </summary>
        internal static string BikeStore {
            get {
                return ResourceManager.GetString("BikeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Posting.
        /// </summary>
        internal static string BlogPosting {
            get {
                return ResourceManager.GetString("BlogPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body of Water.
        /// </summary>
        internal static string BodyOfWater {
            get {
                return ResourceManager.GetString("BodyOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Format Type.
        /// </summary>
        internal static string BookFormatType {
            get {
                return ResourceManager.GetString("BookFormatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Store.
        /// </summary>
        internal static string BookStore {
            get {
                return ResourceManager.GetString("BookStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowling Alley.
        /// </summary>
        internal static string BowlingAlley {
            get {
                return ResourceManager.GetString("BowlingAlley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brewery.
        /// </summary>
        internal static string Brewery {
            get {
                return ResourceManager.GetString("Brewery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddhist Temple.
        /// </summary>
        internal static string BuddhistTemple {
            get {
                return ResourceManager.GetString("BuddhistTemple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Event.
        /// </summary>
        internal static string BusinessEvent {
            get {
                return ResourceManager.GetString("BusinessEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Station.
        /// </summary>
        internal static string BusStation {
            get {
                return ResourceManager.GetString("BusStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Stop.
        /// </summary>
        internal static string BusStop {
            get {
                return ResourceManager.GetString("BusStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe or Coffee Shop.
        /// </summary>
        internal static string CafeOrCoffeeShop {
            get {
                return ResourceManager.GetString("CafeOrCoffeeShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campground.
        /// </summary>
        internal static string Campground {
            get {
                return ResourceManager.GetString("Campground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canal.
        /// </summary>
        internal static string Canal {
            get {
                return ResourceManager.GetString("Canal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino.
        /// </summary>
        internal static string Casino {
            get {
                return ResourceManager.GetString("Casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catholic Church.
        /// </summary>
        internal static string CatholicChurch {
            get {
                return ResourceManager.GetString("CatholicChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cemetery.
        /// </summary>
        internal static string Cemetery {
            get {
                return ResourceManager.GetString("Cemetery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Page.
        /// </summary>
        internal static string CheckoutPage {
            get {
                return ResourceManager.GetString("CheckoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Care.
        /// </summary>
        internal static string ChildCare {
            get {
                return ResourceManager.GetString("ChildCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Childrens Event.
        /// </summary>
        internal static string ChildrensEvent {
            get {
                return ResourceManager.GetString("ChildrensEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church.
        /// </summary>
        internal static string Church {
            get {
                return ResourceManager.GetString("Church", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Hall.
        /// </summary>
        internal static string CityHall {
            get {
                return ResourceManager.GetString("CityHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civic Structure.
        /// </summary>
        internal static string CivicStructure {
            get {
                return ResourceManager.GetString("CivicStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing Store.
        /// </summary>
        internal static string ClothingStore {
            get {
                return ResourceManager.GetString("ClothingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Page.
        /// </summary>
        internal static string CollectionPage {
            get {
                return ResourceManager.GetString("CollectionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College or University.
        /// </summary>
        internal static string CollegeOrUniversity {
            get {
                return ResourceManager.GetString("CollegeOrUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy Club.
        /// </summary>
        internal static string ComedyClub {
            get {
                return ResourceManager.GetString("ComedyClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy Event.
        /// </summary>
        internal static string ComedyEvent {
            get {
                return ResourceManager.GetString("ComedyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Store.
        /// </summary>
        internal static string ComputerStore {
            get {
                return ResourceManager.GetString("ComputerStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Page.
        /// </summary>
        internal static string ContactPage {
            get {
                return ResourceManager.GetString("ContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Point.
        /// </summary>
        internal static string ContactPoint {
            get {
                return ResourceManager.GetString("ContactPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        internal static string Continent {
            get {
                return ResourceManager.GetString("Continent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenience Store.
        /// </summary>
        internal static string ConvenienceStore {
            get {
                return ResourceManager.GetString("ConvenienceStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        internal static string Corporation {
            get {
                return ResourceManager.GetString("Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courthouse.
        /// </summary>
        internal static string Courthouse {
            get {
                return ResourceManager.GetString("Courthouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Work.
        /// </summary>
        internal static string CreativeWork {
            get {
                return ResourceManager.GetString("CreativeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crematorium.
        /// </summary>
        internal static string Crematorium {
            get {
                return ResourceManager.GetString("Crematorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Event.
        /// </summary>
        internal static string DanceEvent {
            get {
                return ResourceManager.GetString("DanceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance Group.
        /// </summary>
        internal static string DanceGroup {
            get {
                return ResourceManager.GetString("DanceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Spa.
        /// </summary>
        internal static string DaySpa {
            get {
                return ResourceManager.GetString("DaySpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defence Establishment.
        /// </summary>
        internal static string DefenceEstablishment {
            get {
                return ResourceManager.GetString("DefenceEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist.
        /// </summary>
        internal static string Dentist {
            get {
                return ResourceManager.GetString("Dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Store.
        /// </summary>
        internal static string DepartmentStore {
            get {
                return ResourceManager.GetString("DepartmentStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Cleaning or Laundry.
        /// </summary>
        internal static string DryCleaningOrLaundry {
            get {
                return ResourceManager.GetString("DryCleaningOrLaundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Organization.
        /// </summary>
        internal static string EducationalOrganization {
            get {
                return ResourceManager.GetString("EducationalOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Event.
        /// </summary>
        internal static string EducationEvent {
            get {
                return ResourceManager.GetString("EducationEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrician.
        /// </summary>
        internal static string Electrician {
            get {
                return ResourceManager.GetString("Electrician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics Store.
        /// </summary>
        internal static string ElectronicsStore {
            get {
                return ResourceManager.GetString("ElectronicsStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary School.
        /// </summary>
        internal static string ElementarySchool {
            get {
                return ResourceManager.GetString("ElementarySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embassy.
        /// </summary>
        internal static string Embassy {
            get {
                return ResourceManager.GetString("Embassy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Service.
        /// </summary>
        internal static string EmergencyService {
            get {
                return ResourceManager.GetString("EmergencyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Agency.
        /// </summary>
        internal static string EmploymentAgency {
            get {
                return ResourceManager.GetString("EmploymentAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment Business.
        /// </summary>
        internal static string EntertainmentBusiness {
            get {
                return ResourceManager.GetString("EntertainmentBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration.
        /// </summary>
        internal static string Enumeration {
            get {
                return ResourceManager.GetString("Enumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Venue.
        /// </summary>
        internal static string EventVenue {
            get {
                return ResourceManager.GetString("EventVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Gym.
        /// </summary>
        internal static string ExerciseGym {
            get {
                return ResourceManager.GetString("ExerciseGym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Food Restaurant.
        /// </summary>
        internal static string FastFoodRestaurant {
            get {
                return ResourceManager.GetString("FastFoodRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festival.
        /// </summary>
        internal static string Festival {
            get {
                return ResourceManager.GetString("Festival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Service.
        /// </summary>
        internal static string FinancialService {
            get {
                return ResourceManager.GetString("FinancialService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Station.
        /// </summary>
        internal static string FireStation {
            get {
                return ResourceManager.GetString("FireStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string Float {
            get {
                return ResourceManager.GetString("Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Florist.
        /// </summary>
        internal static string Florist {
            get {
                return ResourceManager.GetString("Florist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Establishment.
        /// </summary>
        internal static string FoodEstablishment {
            get {
                return ResourceManager.GetString("FoodEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Event.
        /// </summary>
        internal static string FoodEvent {
            get {
                return ResourceManager.GetString("FoodEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furniture Store.
        /// </summary>
        internal static string FurnitureStore {
            get {
                return ResourceManager.GetString("FurnitureStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden Store.
        /// </summary>
        internal static string GardenStore {
            get {
                return ResourceManager.GetString("GardenStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Station.
        /// </summary>
        internal static string GasStation {
            get {
                return ResourceManager.GetString("GasStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gated Residence Community.
        /// </summary>
        internal static string GatedResidenceCommunity {
            get {
                return ResourceManager.GetString("GatedResidenceCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Contractor.
        /// </summary>
        internal static string GeneralContractor {
            get {
                return ResourceManager.GetString("GeneralContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Coordinates.
        /// </summary>
        internal static string GeoCoordinates {
            get {
                return ResourceManager.GetString("GeoCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Shape.
        /// </summary>
        internal static string GeoShape {
            get {
                return ResourceManager.GetString("GeoShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf Course.
        /// </summary>
        internal static string GolfCourse {
            get {
                return ResourceManager.GetString("GolfCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Building.
        /// </summary>
        internal static string GovernmentBuilding {
            get {
                return ResourceManager.GetString("GovernmentBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Office.
        /// </summary>
        internal static string GovernmentOffice {
            get {
                return ResourceManager.GetString("GovernmentOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Organization.
        /// </summary>
        internal static string GovernmentOrganization {
            get {
                return ResourceManager.GetString("GovernmentOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grocery Store.
        /// </summary>
        internal static string GroceryStore {
            get {
                return ResourceManager.GetString("GroceryStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Salon.
        /// </summary>
        internal static string HairSalon {
            get {
                return ResourceManager.GetString("HairSalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Store.
        /// </summary>
        internal static string HardwareStore {
            get {
                return ResourceManager.GetString("HardwareStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health And Beauty Business.
        /// </summary>
        internal static string HealthAndBeautyBusiness {
            get {
                return ResourceManager.GetString("HealthAndBeautyBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Club.
        /// </summary>
        internal static string HealthClub {
            get {
                return ResourceManager.GetString("HealthClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High School.
        /// </summary>
        internal static string HighSchool {
            get {
                return ResourceManager.GetString("HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindu Temple.
        /// </summary>
        internal static string HinduTemple {
            get {
                return ResourceManager.GetString("HinduTemple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby Shop.
        /// </summary>
        internal static string HobbyShop {
            get {
                return ResourceManager.GetString("HobbyShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home And Construction Business.
        /// </summary>
        internal static string HomeAndConstructionBusiness {
            get {
                return ResourceManager.GetString("HomeAndConstructionBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Goods Store.
        /// </summary>
        internal static string HomeGoodsStore {
            get {
                return ResourceManager.GetString("HomeGoodsStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        internal static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostel.
        /// </summary>
        internal static string Hostel {
            get {
                return ResourceManager.GetString("Hostel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Painter.
        /// </summary>
        internal static string HousePainter {
            get {
                return ResourceManager.GetString("HousePainter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVAC Business.
        /// </summary>
        internal static string HVACBusiness {
            get {
                return ResourceManager.GetString("HVACBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Cream Shop.
        /// </summary>
        internal static string IceCreamShop {
            get {
                return ResourceManager.GetString("IceCreamShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Gallery.
        /// </summary>
        internal static string ImageGallery {
            get {
                return ResourceManager.GetString("ImageGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Object.
        /// </summary>
        internal static string ImageObject {
            get {
                return ResourceManager.GetString("ImageObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Agency.
        /// </summary>
        internal static string InsuranceAgency {
            get {
                return ResourceManager.GetString("InsuranceAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intangible.
        /// </summary>
        internal static string Intangible {
            get {
                return ResourceManager.GetString("Intangible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Cafe.
        /// </summary>
        internal static string InternetCafe {
            get {
                return ResourceManager.GetString("InternetCafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Availability.
        /// </summary>
        internal static string ItemAvailability {
            get {
                return ResourceManager.GetString("ItemAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List.
        /// </summary>
        internal static string ItemList {
            get {
                return ResourceManager.GetString("ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Page.
        /// </summary>
        internal static string ItemPage {
            get {
                return ResourceManager.GetString("ItemPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry Store.
        /// </summary>
        internal static string JewelryStore {
            get {
                return ResourceManager.GetString("JewelryStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Posting.
        /// </summary>
        internal static string JobPosting {
            get {
                return ResourceManager.GetString("JobPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lake Body of Water.
        /// </summary>
        internal static string LakeBodyOfWater {
            get {
                return ResourceManager.GetString("LakeBodyOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landform.
        /// </summary>
        internal static string Landform {
            get {
                return ResourceManager.GetString("Landform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmarks or Historical Buildings.
        /// </summary>
        internal static string LandmarksOrHistoricalBuildings {
            get {
                return ResourceManager.GetString("LandmarksOrHistoricalBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislative Building.
        /// </summary>
        internal static string LegislativeBuilding {
            get {
                return ResourceManager.GetString("LegislativeBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquor Store.
        /// </summary>
        internal static string LiquorStore {
            get {
                return ResourceManager.GetString("LiquorStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literary Event.
        /// </summary>
        internal static string LiteraryEvent {
            get {
                return ResourceManager.GetString("LiteraryEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Business.
        /// </summary>
        internal static string LocalBusiness {
            get {
                return ResourceManager.GetString("LocalBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locksmith.
        /// </summary>
        internal static string Locksmith {
            get {
                return ResourceManager.GetString("Locksmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lodging Business.
        /// </summary>
        internal static string LodgingBusiness {
            get {
                return ResourceManager.GetString("LodgingBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        internal static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Object.
        /// </summary>
        internal static string MediaObject {
            get {
                return ResourceManager.GetString("MediaObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Clinic.
        /// </summary>
        internal static string MedicalClinic {
            get {
                return ResourceManager.GetString("MedicalClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Organization.
        /// </summary>
        internal static string MedicalOrganization {
            get {
                return ResourceManager.GetString("MedicalOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mens Clothing Store.
        /// </summary>
        internal static string MensClothingStore {
            get {
                return ResourceManager.GetString("MensClothingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle School.
        /// </summary>
        internal static string MiddleSchool {
            get {
                return ResourceManager.GetString("MiddleSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone Store.
        /// </summary>
        internal static string MobilePhoneStore {
            get {
                return ResourceManager.GetString("MobilePhoneStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosque.
        /// </summary>
        internal static string Mosque {
            get {
                return ResourceManager.GetString("Mosque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motel.
        /// </summary>
        internal static string Motel {
            get {
                return ResourceManager.GetString("Motel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle Dealer.
        /// </summary>
        internal static string MotorcycleDealer {
            get {
                return ResourceManager.GetString("MotorcycleDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle Repair.
        /// </summary>
        internal static string MotorcycleRepair {
            get {
                return ResourceManager.GetString("MotorcycleRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain.
        /// </summary>
        internal static string Mountain {
            get {
                return ResourceManager.GetString("Mountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Rental Store.
        /// </summary>
        internal static string MovieRentalStore {
            get {
                return ResourceManager.GetString("MovieRentalStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Theater.
        /// </summary>
        internal static string MovieTheater {
            get {
                return ResourceManager.GetString("MovieTheater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving Company.
        /// </summary>
        internal static string MovingCompany {
            get {
                return ResourceManager.GetString("MovingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Museum.
        /// </summary>
        internal static string Museum {
            get {
                return ResourceManager.GetString("Museum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Album.
        /// </summary>
        internal static string MusicAlbum {
            get {
                return ResourceManager.GetString("MusicAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Event.
        /// </summary>
        internal static string MusicEvent {
            get {
                return ResourceManager.GetString("MusicEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Group.
        /// </summary>
        internal static string MusicGroup {
            get {
                return ResourceManager.GetString("MusicGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Playlist.
        /// </summary>
        internal static string MusicPlaylist {
            get {
                return ResourceManager.GetString("MusicPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Recording.
        /// </summary>
        internal static string MusicRecording {
            get {
                return ResourceManager.GetString("MusicRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Store.
        /// </summary>
        internal static string MusicStore {
            get {
                return ResourceManager.GetString("MusicStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Venue.
        /// </summary>
        internal static string MusicVenue {
            get {
                return ResourceManager.GetString("MusicVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Video Object.
        /// </summary>
        internal static string MusicVideoObject {
            get {
                return ResourceManager.GetString("MusicVideoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nail Salon.
        /// </summary>
        internal static string NailSalon {
            get {
                return ResourceManager.GetString("NailSalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Article.
        /// </summary>
        internal static string NewsArticle {
            get {
                return ResourceManager.GetString("NewsArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGO.
        /// </summary>
        internal static string NGO {
            get {
                return ResourceManager.GetString("NGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Club.
        /// </summary>
        internal static string NightClub {
            get {
                return ResourceManager.GetString("NightClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notary.
        /// </summary>
        internal static string Notary {
            get {
                return ResourceManager.GetString("Notary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutrition Information.
        /// </summary>
        internal static string NutritionInformation {
            get {
                return ResourceManager.GetString("NutritionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean Body of Water.
        /// </summary>
        internal static string OceanBodyOfWater {
            get {
                return ResourceManager.GetString("OceanBodyOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        internal static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Item Condition.
        /// </summary>
        internal static string OfferItemCondition {
            get {
                return ResourceManager.GetString("OfferItemCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Equipment Store.
        /// </summary>
        internal static string OfficeEquipmentStore {
            get {
                return ResourceManager.GetString("OfficeEquipmentStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optician.
        /// </summary>
        internal static string Optician {
            get {
                return ResourceManager.GetString("Optician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlet Store.
        /// </summary>
        internal static string OutletStore {
            get {
                return ResourceManager.GetString("OutletStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting.
        /// </summary>
        internal static string Painting {
            get {
                return ResourceManager.GetString("Painting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        internal static string Park {
            get {
                return ResourceManager.GetString("Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking Facility.
        /// </summary>
        internal static string ParkingFacility {
            get {
                return ResourceManager.GetString("ParkingFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn Shop.
        /// </summary>
        internal static string PawnShop {
            get {
                return ResourceManager.GetString("PawnShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing Arts Theater.
        /// </summary>
        internal static string PerformingArtsTheater {
            get {
                return ResourceManager.GetString("PerformingArtsTheater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing Group.
        /// </summary>
        internal static string PerformingGroup {
            get {
                return ResourceManager.GetString("PerformingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Store.
        /// </summary>
        internal static string PetStore {
            get {
                return ResourceManager.GetString("PetStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy.
        /// </summary>
        internal static string Pharmacy {
            get {
                return ResourceManager.GetString("Pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photograph.
        /// </summary>
        internal static string Photograph {
            get {
                return ResourceManager.GetString("Photograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        internal static string Physician {
            get {
                return ResourceManager.GetString("Physician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Worship.
        /// </summary>
        internal static string PlaceOfWorship {
            get {
                return ResourceManager.GetString("PlaceOfWorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playground.
        /// </summary>
        internal static string Playground {
            get {
                return ResourceManager.GetString("Playground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumber.
        /// </summary>
        internal static string Plumber {
            get {
                return ResourceManager.GetString("Plumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Station.
        /// </summary>
        internal static string PoliceStation {
            get {
                return ResourceManager.GetString("PoliceStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pond.
        /// </summary>
        internal static string Pond {
            get {
                return ResourceManager.GetString("Pond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Address.
        /// </summary>
        internal static string PostalAddress {
            get {
                return ResourceManager.GetString("PostalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Office.
        /// </summary>
        internal static string PostOffice {
            get {
                return ResourceManager.GetString("PostOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preschool.
        /// </summary>
        internal static string Preschool {
            get {
                return ResourceManager.GetString("Preschool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Service.
        /// </summary>
        internal static string ProfessionalService {
            get {
                return ResourceManager.GetString("ProfessionalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Page.
        /// </summary>
        internal static string ProfilePage {
            get {
                return ResourceManager.GetString("ProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Swimming Pool.
        /// </summary>
        internal static string PublicSwimmingPool {
            get {
                return ResourceManager.GetString("PublicSwimmingPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Station.
        /// </summary>
        internal static string RadioStation {
            get {
                return ResourceManager.GetString("RadioStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate Agent.
        /// </summary>
        internal static string RealEstateAgent {
            get {
                return ResourceManager.GetString("RealEstateAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        internal static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycling Center.
        /// </summary>
        internal static string RecyclingCenter {
            get {
                return ResourceManager.GetString("RecyclingCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservoir.
        /// </summary>
        internal static string Reservoir {
            get {
                return ResourceManager.GetString("Reservoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence.
        /// </summary>
        internal static string Residence {
            get {
                return ResourceManager.GetString("Residence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River Body of Water.
        /// </summary>
        internal static string RiverBodyOfWater {
            get {
                return ResourceManager.GetString("RiverBodyOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roofing Contractor.
        /// </summary>
        internal static string RoofingContractor {
            get {
                return ResourceManager.GetString("RoofingContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RV Park.
        /// </summary>
        internal static string RVPark {
            get {
                return ResourceManager.GetString("RVPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Event.
        /// </summary>
        internal static string SaleEvent {
            get {
                return ResourceManager.GetString("SaleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholarly Article.
        /// </summary>
        internal static string ScholarlyArticle {
            get {
                return ResourceManager.GetString("ScholarlyArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        internal static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sculpture.
        /// </summary>
        internal static string Sculpture {
            get {
                return ResourceManager.GetString("Sculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Body of Water.
        /// </summary>
        internal static string SeaBodyOfWater {
            get {
                return ResourceManager.GetString("SeaBodyOfWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results Page.
        /// </summary>
        internal static string SearchResultsPage {
            get {
                return ResourceManager.GetString("SearchResultsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Storage.
        /// </summary>
        internal static string SelfStorage {
            get {
                return ResourceManager.GetString("SelfStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoe Store.
        /// </summary>
        internal static string ShoeStore {
            get {
                return ResourceManager.GetString("ShoeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Center.
        /// </summary>
        internal static string ShoppingCenter {
            get {
                return ResourceManager.GetString("ShoppingCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Family Residence.
        /// </summary>
        internal static string SingleFamilyResidence {
            get {
                return ResourceManager.GetString("SingleFamilyResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Navigation Element.
        /// </summary>
        internal static string SiteNavigationElement {
            get {
                return ResourceManager.GetString("SiteNavigationElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ski Resort.
        /// </summary>
        internal static string SkiResort {
            get {
                return ResourceManager.GetString("SkiResort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Event.
        /// </summary>
        internal static string SocialEvent {
            get {
                return ResourceManager.GetString("SocialEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporting Goods Store.
        /// </summary>
        internal static string SportingGoodsStore {
            get {
                return ResourceManager.GetString("SportingGoodsStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Activity Location.
        /// </summary>
        internal static string SportsActivityLocation {
            get {
                return ResourceManager.GetString("SportsActivityLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Club.
        /// </summary>
        internal static string SportsClub {
            get {
                return ResourceManager.GetString("SportsClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Event.
        /// </summary>
        internal static string SportsEvent {
            get {
                return ResourceManager.GetString("SportsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Team.
        /// </summary>
        internal static string SportsTeam {
            get {
                return ResourceManager.GetString("SportsTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadium or Arena.
        /// </summary>
        internal static string StadiumOrArena {
            get {
                return ResourceManager.GetString("StadiumOrArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Value.
        /// </summary>
        internal static string StructuredValue {
            get {
                return ResourceManager.GetString("StructuredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subway Station.
        /// </summary>
        internal static string SubwayStation {
            get {
                return ResourceManager.GetString("SubwayStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synagogue.
        /// </summary>
        internal static string Synagogue {
            get {
                return ResourceManager.GetString("Synagogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tattoo Parlor.
        /// </summary>
        internal static string TattooParlor {
            get {
                return ResourceManager.GetString("TattooParlor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi Stand.
        /// </summary>
        internal static string TaxiStand {
            get {
                return ResourceManager.GetString("TaxiStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Television Station.
        /// </summary>
        internal static string TelevisionStation {
            get {
                return ResourceManager.GetString("TelevisionStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennis Complex.
        /// </summary>
        internal static string TennisComplex {
            get {
                return ResourceManager.GetString("TennisComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theater Event.
        /// </summary>
        internal static string TheaterEvent {
            get {
                return ResourceManager.GetString("TheaterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theater Group.
        /// </summary>
        internal static string TheaterGroup {
            get {
                return ResourceManager.GetString("TheaterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing.
        /// </summary>
        internal static string Thing {
            get {
                return ResourceManager.GetString("Thing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tire Shop.
        /// </summary>
        internal static string TireShop {
            get {
                return ResourceManager.GetString("TireShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Attraction.
        /// </summary>
        internal static string TouristAttraction {
            get {
                return ResourceManager.GetString("TouristAttraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tourist Information Center.
        /// </summary>
        internal static string TouristInformationCenter {
            get {
                return ResourceManager.GetString("TouristInformationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toy Store.
        /// </summary>
        internal static string ToyStore {
            get {
                return ResourceManager.GetString("ToyStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Station.
        /// </summary>
        internal static string TrainStation {
            get {
                return ResourceManager.GetString("TrainStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Agency.
        /// </summary>
        internal static string TravelAgency {
            get {
                return ResourceManager.GetString("TravelAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Episode.
        /// </summary>
        internal static string TVEpisode {
            get {
                return ResourceManager.GetString("TVEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Season.
        /// </summary>
        internal static string TVSeason {
            get {
                return ResourceManager.GetString("TVSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Series.
        /// </summary>
        internal static string TVSeries {
            get {
                return ResourceManager.GetString("TVSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Blocks.
        /// </summary>
        internal static string UserBlocks {
            get {
                return ResourceManager.GetString("UserBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Checkins.
        /// </summary>
        internal static string UserCheckins {
            get {
                return ResourceManager.GetString("UserCheckins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Comments.
        /// </summary>
        internal static string UserComments {
            get {
                return ResourceManager.GetString("UserComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Downloads.
        /// </summary>
        internal static string UserDownloads {
            get {
                return ResourceManager.GetString("UserDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interaction.
        /// </summary>
        internal static string UserInteraction {
            get {
                return ResourceManager.GetString("UserInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Likes.
        /// </summary>
        internal static string UserLikes {
            get {
                return ResourceManager.GetString("UserLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Page Visits.
        /// </summary>
        internal static string UserPageVisits {
            get {
                return ResourceManager.GetString("UserPageVisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Plays.
        /// </summary>
        internal static string UserPlays {
            get {
                return ResourceManager.GetString("UserPlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Plus Ones.
        /// </summary>
        internal static string UserPlusOnes {
            get {
                return ResourceManager.GetString("UserPlusOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Tweets.
        /// </summary>
        internal static string UserTweets {
            get {
                return ResourceManager.GetString("UserTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veterinary Care.
        /// </summary>
        internal static string VeterinaryCare {
            get {
                return ResourceManager.GetString("VeterinaryCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Gallery.
        /// </summary>
        internal static string VideoGallery {
            get {
                return ResourceManager.GetString("VideoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Object.
        /// </summary>
        internal static string VideoObject {
            get {
                return ResourceManager.GetString("VideoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Arts Event.
        /// </summary>
        internal static string VisualArtsEvent {
            get {
                return ResourceManager.GetString("VisualArtsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volcano.
        /// </summary>
        internal static string Volcano {
            get {
                return ResourceManager.GetString("Volcano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterfall.
        /// </summary>
        internal static string Waterfall {
            get {
                return ResourceManager.GetString("Waterfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Page.
        /// </summary>
        internal static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Page Element.
        /// </summary>
        internal static string WebPageElement {
            get {
                return ResourceManager.GetString("WebPageElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Store.
        /// </summary>
        internal static string WholesaleStore {
            get {
                return ResourceManager.GetString("WholesaleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winery.
        /// </summary>
        internal static string Winery {
            get {
                return ResourceManager.GetString("Winery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP Ad Block.
        /// </summary>
        internal static string WPAdBlock {
            get {
                return ResourceManager.GetString("WPAdBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP Footer.
        /// </summary>
        internal static string WPFooter {
            get {
                return ResourceManager.GetString("WPFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP Header.
        /// </summary>
        internal static string WPHeader {
            get {
                return ResourceManager.GetString("WPHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP Side Bar.
        /// </summary>
        internal static string WPSideBar {
            get {
                return ResourceManager.GetString("WPSideBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoo.
        /// </summary>
        internal static string Zoo {
            get {
                return ResourceManager.GetString("Zoo", resourceCulture);
            }
        }
    }
}
