//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sasoma.Api.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sasoma.Api.Languages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;About&quot; is not valid..
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Accepts Reservations&quot; is not a valid text or URL..
        /// </summary>
        internal static string acceptsReservations {
            get {
                return ResourceManager.GetString("acceptsReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Accountable Person&quot; is not valid..
        /// </summary>
        internal static string accountablePerson {
            get {
                return ResourceManager.GetString("accountablePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Actors&quot; is not valid..
        /// </summary>
        internal static string actors {
            get {
                return ResourceManager.GetString("actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Additional Name&quot; is not valid..
        /// </summary>
        internal static string additionalName {
            get {
                return ResourceManager.GetString("additionalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Address&quot; is not valid..
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Address Country&quot; is not valid..
        /// </summary>
        internal static string addressCountry {
            get {
                return ResourceManager.GetString("addressCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Address Locality&quot; is not valid..
        /// </summary>
        internal static string addressLocality {
            get {
                return ResourceManager.GetString("addressLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Address Region&quot; is not valid..
        /// </summary>
        internal static string addressRegion {
            get {
                return ResourceManager.GetString("addressRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Affiliation&quot; is not valid..
        /// </summary>
        internal static string affiliation {
            get {
                return ResourceManager.GetString("affiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Aggregate Rating&quot; is not valid..
        /// </summary>
        internal static string aggregateRating {
            get {
                return ResourceManager.GetString("aggregateRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Albums&quot; is not valid..
        /// </summary>
        internal static string albums {
            get {
                return ResourceManager.GetString("albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Alternative Headline&quot; is not valid..
        /// </summary>
        internal static string alternativeHeadline {
            get {
                return ResourceManager.GetString("alternativeHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Alumni&quot; is not valid..
        /// </summary>
        internal static string alumni {
            get {
                return ResourceManager.GetString("alumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Alumni of&quot; is not valid..
        /// </summary>
        internal static string alumniOf {
            get {
                return ResourceManager.GetString("alumniOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Article Body&quot; is not valid..
        /// </summary>
        internal static string articleBody {
            get {
                return ResourceManager.GetString("articleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Article Section&quot; is not valid..
        /// </summary>
        internal static string articleSection {
            get {
                return ResourceManager.GetString("articleSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Associated Article&quot; is not valid..
        /// </summary>
        internal static string associatedArticle {
            get {
                return ResourceManager.GetString("associatedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Associated Media&quot; is not valid..
        /// </summary>
        internal static string associatedMedia {
            get {
                return ResourceManager.GetString("associatedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Attendees&quot; is not valid..
        /// </summary>
        internal static string attendees {
            get {
                return ResourceManager.GetString("attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Audio&quot; is not valid..
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Author&quot; is not valid..
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Availability&quot; is not valid..
        /// </summary>
        internal static string availability {
            get {
                return ResourceManager.GetString("availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Awards&quot; is not valid..
        /// </summary>
        internal static string awards {
            get {
                return ResourceManager.GetString("awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that &quot;Base Salary&quot; is a valid number..
        /// </summary>
        internal static string baseSalary {
            get {
                return ResourceManager.GetString("baseSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Benefits&quot; is not valid..
        /// </summary>
        internal static string benefits {
            get {
                return ResourceManager.GetString("benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Best Rating&quot; is not an alphanumeric value..
        /// </summary>
        internal static string bestRating {
            get {
                return ResourceManager.GetString("bestRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Birth Date&quot; is a valid date..
        /// </summary>
        internal static string birthDate {
            get {
                return ResourceManager.GetString("birthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Bitrate&quot; is not valid..
        /// </summary>
        internal static string bitrate {
            get {
                return ResourceManager.GetString("bitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Blog Posts&quot; is not valid..
        /// </summary>
        internal static string blogPosts {
            get {
                return ResourceManager.GetString("blogPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Book Edition&quot; is not valid..
        /// </summary>
        internal static string bookEdition {
            get {
                return ResourceManager.GetString("bookEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Book Format&quot; is not valid..
        /// </summary>
        internal static string bookFormat {
            get {
                return ResourceManager.GetString("bookFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Box&quot; is not valid..
        /// </summary>
        internal static string box {
            get {
                return ResourceManager.GetString("box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Branch of&quot; is not valid..
        /// </summary>
        internal static string branchOf {
            get {
                return ResourceManager.GetString("branchOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Brand&quot; is not valid..
        /// </summary>
        internal static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Breadcrumb&quot; is not valid..
        /// </summary>
        internal static string breadcrumb {
            get {
                return ResourceManager.GetString("breadcrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;By Artist&quot; is not valid..
        /// </summary>
        internal static string byArtist {
            get {
                return ResourceManager.GetString("byArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Calories&quot; is not valid..
        /// </summary>
        internal static string calories {
            get {
                return ResourceManager.GetString("calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Caption&quot; is not valid..
        /// </summary>
        internal static string caption {
            get {
                return ResourceManager.GetString("caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Carbohydrate Content&quot; is not valid..
        /// </summary>
        internal static string carbohydrateContent {
            get {
                return ResourceManager.GetString("carbohydrateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Children&quot; is not valid..
        /// </summary>
        internal static string children {
            get {
                return ResourceManager.GetString("children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cholesterol Content&quot; is not valid..
        /// </summary>
        internal static string cholesterolContent {
            get {
                return ResourceManager.GetString("cholesterolContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Circle&quot; is not valid..
        /// </summary>
        internal static string circle {
            get {
                return ResourceManager.GetString("circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Colleagues&quot; is not valid..
        /// </summary>
        internal static string colleagues {
            get {
                return ResourceManager.GetString("colleagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Comment&quot; is not valid..
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Comment Text&quot; is not valid..
        /// </summary>
        internal static string commentText {
            get {
                return ResourceManager.GetString("commentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Comment Time&quot; is a valid date..
        /// </summary>
        internal static string commentTime {
            get {
                return ResourceManager.GetString("commentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Contact Points&quot; is not valid..
        /// </summary>
        internal static string contactPoints {
            get {
                return ResourceManager.GetString("contactPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Contact Type&quot; is not valid..
        /// </summary>
        internal static string contactType {
            get {
                return ResourceManager.GetString("contactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Contained in&quot; is not valid..
        /// </summary>
        internal static string containedIn {
            get {
                return ResourceManager.GetString("containedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Content Location&quot; is not valid..
        /// </summary>
        internal static string contentLocation {
            get {
                return ResourceManager.GetString("contentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Content Rating&quot; is not valid..
        /// </summary>
        internal static string contentRating {
            get {
                return ResourceManager.GetString("contentRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Content Size&quot; is not valid..
        /// </summary>
        internal static string contentSize {
            get {
                return ResourceManager.GetString("contentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Content URL&quot; is not a valid URL..
        /// </summary>
        internal static string contentURL {
            get {
                return ResourceManager.GetString("contentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Contributor&quot; is not valid..
        /// </summary>
        internal static string contributor {
            get {
                return ResourceManager.GetString("contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cooking Method&quot; is not valid..
        /// </summary>
        internal static string cookingMethod {
            get {
                return ResourceManager.GetString("cookingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Cook Time&quot; is a valid number..
        /// </summary>
        internal static string cookTime {
            get {
                return ResourceManager.GetString("cookTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Copyright Holder&quot; is not valid..
        /// </summary>
        internal static string copyrightHolder {
            get {
                return ResourceManager.GetString("copyrightHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that &quot;Copyright Year&quot; is a valid number..
        /// </summary>
        internal static string copyrightYear {
            get {
                return ResourceManager.GetString("copyrightYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Creator&quot; is not valid..
        /// </summary>
        internal static string creator {
            get {
                return ResourceManager.GetString("creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Currencies Accepted&quot; is not valid..
        /// </summary>
        internal static string currenciesAccepted {
            get {
                return ResourceManager.GetString("currenciesAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Date Created&quot; is a valid date..
        /// </summary>
        internal static string dateCreated {
            get {
                return ResourceManager.GetString("dateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dateline&quot; is not valid..
        /// </summary>
        internal static string dateline {
            get {
                return ResourceManager.GetString("dateline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Date Modified&quot; is a valid date..
        /// </summary>
        internal static string dateModified {
            get {
                return ResourceManager.GetString("dateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Date Posted&quot; is a valid date..
        /// </summary>
        internal static string datePosted {
            get {
                return ResourceManager.GetString("datePosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Date Published&quot; is a valid date..
        /// </summary>
        internal static string datePublished {
            get {
                return ResourceManager.GetString("datePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Death Date&quot; is a valid date..
        /// </summary>
        internal static string deathDate {
            get {
                return ResourceManager.GetString("deathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Description&quot; is not valid..
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Director&quot; is not valid..
        /// </summary>
        internal static string director {
            get {
                return ResourceManager.GetString("director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Discusses&quot; is not valid..
        /// </summary>
        internal static string discusses {
            get {
                return ResourceManager.GetString("discusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Discussion Url&quot; is not a valid URL..
        /// </summary>
        internal static string discussionUrl {
            get {
                return ResourceManager.GetString("discussionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Duration&quot; is a valid number..
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Editor&quot; is not valid..
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Education Requirements&quot; is not valid..
        /// </summary>
        internal static string educationRequirements {
            get {
                return ResourceManager.GetString("educationRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Elevation&quot; is not valid..
        /// </summary>
        internal static string elevation {
            get {
                return ResourceManager.GetString("elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Email&quot; is not valid..
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Embed URL&quot; is not a valid URL..
        /// </summary>
        internal static string embedURL {
            get {
                return ResourceManager.GetString("embedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Employees&quot; is not valid..
        /// </summary>
        internal static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Employment Type&quot; is not valid..
        /// </summary>
        internal static string employmentType {
            get {
                return ResourceManager.GetString("employmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Encodes Creative Work&quot; is not valid..
        /// </summary>
        internal static string encodesCreativeWork {
            get {
                return ResourceManager.GetString("encodesCreativeWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Encoding Format&quot; is not valid..
        /// </summary>
        internal static string encodingFormat {
            get {
                return ResourceManager.GetString("encodingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Encodings&quot; is not valid..
        /// </summary>
        internal static string encodings {
            get {
                return ResourceManager.GetString("encodings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;End Date&quot; is a valid date..
        /// </summary>
        internal static string endDate {
            get {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that &quot;Episode Number&quot; is a valid number..
        /// </summary>
        internal static string episodeNumber {
            get {
                return ResourceManager.GetString("episodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Episodes&quot; is not valid..
        /// </summary>
        internal static string episodes {
            get {
                return ResourceManager.GetString("episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Events&quot; is not valid..
        /// </summary>
        internal static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Exif Data&quot; is not valid..
        /// </summary>
        internal static string exifData {
            get {
                return ResourceManager.GetString("exifData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Experience Requirements&quot; is not valid..
        /// </summary>
        internal static string experienceRequirements {
            get {
                return ResourceManager.GetString("experienceRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Expires&quot; is a valid date..
        /// </summary>
        internal static string expires {
            get {
                return ResourceManager.GetString("expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Family Name&quot; is not valid..
        /// </summary>
        internal static string familyName {
            get {
                return ResourceManager.GetString("familyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Fat Content&quot; is not valid..
        /// </summary>
        internal static string fatContent {
            get {
                return ResourceManager.GetString("fatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Fax Number&quot; is not valid..
        /// </summary>
        internal static string faxNumber {
            get {
                return ResourceManager.GetString("faxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Fiber Content&quot; is not valid..
        /// </summary>
        internal static string fiberContent {
            get {
                return ResourceManager.GetString("fiberContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Follows&quot; is not valid..
        /// </summary>
        internal static string follows {
            get {
                return ResourceManager.GetString("follows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Founders&quot; is not valid..
        /// </summary>
        internal static string founders {
            get {
                return ResourceManager.GetString("founders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Founding Date&quot; is a valid date..
        /// </summary>
        internal static string foundingDate {
            get {
                return ResourceManager.GetString("foundingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Gender&quot; is not valid..
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Genre&quot; is not valid..
        /// </summary>
        internal static string genre {
            get {
                return ResourceManager.GetString("genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Geo&quot; is not valid..
        /// </summary>
        internal static string geo {
            get {
                return ResourceManager.GetString("geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Given Name&quot; is not valid..
        /// </summary>
        internal static string givenName {
            get {
                return ResourceManager.GetString("givenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Headline&quot; is not valid..
        /// </summary>
        internal static string headline {
            get {
                return ResourceManager.GetString("headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Height&quot; is not valid..
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;High Price&quot; is not an alphanumeric value..
        /// </summary>
        internal static string highPrice {
            get {
                return ResourceManager.GetString("highPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Hiring Organization&quot; is not valid..
        /// </summary>
        internal static string hiringOrganization {
            get {
                return ResourceManager.GetString("hiringOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Home Location&quot; is not valid..
        /// </summary>
        internal static string homeLocation {
            get {
                return ResourceManager.GetString("homeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Honorific Prefix&quot; is not valid..
        /// </summary>
        internal static string honorificPrefix {
            get {
                return ResourceManager.GetString("honorificPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Honorific Suffix&quot; is not valid..
        /// </summary>
        internal static string honorificSuffix {
            get {
                return ResourceManager.GetString("honorificSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Illustrator&quot; is not valid..
        /// </summary>
        internal static string illustrator {
            get {
                return ResourceManager.GetString("illustrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Image&quot; is not a valid URL..
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;In Album&quot; is not valid..
        /// </summary>
        internal static string inAlbum {
            get {
                return ResourceManager.GetString("inAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Incentives&quot; is not valid..
        /// </summary>
        internal static string incentives {
            get {
                return ResourceManager.GetString("incentives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Industry&quot; is not valid..
        /// </summary>
        internal static string industry {
            get {
                return ResourceManager.GetString("industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Ingredients&quot; is not valid..
        /// </summary>
        internal static string ingredients {
            get {
                return ResourceManager.GetString("ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;In Language&quot; is not valid..
        /// </summary>
        internal static string inLanguage {
            get {
                return ResourceManager.GetString("inLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;In Playlist&quot; is not valid..
        /// </summary>
        internal static string inPlaylist {
            get {
                return ResourceManager.GetString("inPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Interaction Count&quot; is not valid..
        /// </summary>
        internal static string interactionCount {
            get {
                return ResourceManager.GetString("interactionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ISBN&quot; is not valid..
        /// </summary>
        internal static string isbn {
            get {
                return ResourceManager.GetString("isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Is Family Friendly&quot; can only have one of the values, true or false..
        /// </summary>
        internal static string isFamilyFriendly {
            get {
                return ResourceManager.GetString("isFamilyFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Is Part of&quot; is not valid..
        /// </summary>
        internal static string isPartOf {
            get {
                return ResourceManager.GetString("isPartOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Item Condition&quot; is not valid..
        /// </summary>
        internal static string itemCondition {
            get {
                return ResourceManager.GetString("itemCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Item List Element&quot; is not valid..
        /// </summary>
        internal static string itemListElement {
            get {
                return ResourceManager.GetString("itemListElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Item List Order&quot; is not valid..
        /// </summary>
        internal static string itemListOrder {
            get {
                return ResourceManager.GetString("itemListOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Item Offered&quot; is not valid..
        /// </summary>
        internal static string itemOffered {
            get {
                return ResourceManager.GetString("itemOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Item Reviewed&quot; is not valid..
        /// </summary>
        internal static string itemReviewed {
            get {
                return ResourceManager.GetString("itemReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Job Location&quot; is not valid..
        /// </summary>
        internal static string jobLocation {
            get {
                return ResourceManager.GetString("jobLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Job Title&quot; is not valid..
        /// </summary>
        internal static string jobTitle {
            get {
                return ResourceManager.GetString("jobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Keywords&quot; is not valid..
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Knows&quot; is not valid..
        /// </summary>
        internal static string knows {
            get {
                return ResourceManager.GetString("knows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Latitude&quot; is not an alphanumeric value..
        /// </summary>
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Line&quot; is not valid..
        /// </summary>
        internal static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Location&quot; is not valid..
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Longitude&quot; is not an alphanumeric value..
        /// </summary>
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Low Price&quot; is not an alphanumeric value..
        /// </summary>
        internal static string lowPrice {
            get {
                return ResourceManager.GetString("lowPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Main Content of Page&quot; is not valid..
        /// </summary>
        internal static string mainContentOfPage {
            get {
                return ResourceManager.GetString("mainContentOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Manufacturer&quot; is not valid..
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Maps&quot; is not a valid URL..
        /// </summary>
        internal static string maps {
            get {
                return ResourceManager.GetString("maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Member of&quot; is not valid..
        /// </summary>
        internal static string memberOf {
            get {
                return ResourceManager.GetString("memberOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Members&quot; is not valid..
        /// </summary>
        internal static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Mentions&quot; is not valid..
        /// </summary>
        internal static string mentions {
            get {
                return ResourceManager.GetString("mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Menu&quot; is not a valid text or URL..
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Model&quot; is not valid..
        /// </summary>
        internal static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Music by&quot; is not valid..
        /// </summary>
        internal static string musicBy {
            get {
                return ResourceManager.GetString("musicBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Music Group Member&quot; is not valid..
        /// </summary>
        internal static string musicGroupMember {
            get {
                return ResourceManager.GetString("musicGroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Name&quot; is not valid..
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nationality&quot; is not valid..
        /// </summary>
        internal static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that &quot;Number of Episodes&quot; is a valid number..
        /// </summary>
        internal static string numberOfEpisodes {
            get {
                return ResourceManager.GetString("numberOfEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Number of Pages&quot; must be a valid integer..
        /// </summary>
        internal static string numberOfPages {
            get {
                return ResourceManager.GetString("numberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Num Tracks&quot; must be a valid integer..
        /// </summary>
        internal static string numTracks {
            get {
                return ResourceManager.GetString("numTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nutrition&quot; is not valid..
        /// </summary>
        internal static string nutrition {
            get {
                return ResourceManager.GetString("nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Occupational Category&quot; is not valid..
        /// </summary>
        internal static string occupationalCategory {
            get {
                return ResourceManager.GetString("occupationalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Offer Count&quot; must be a valid integer..
        /// </summary>
        internal static string offerCount {
            get {
                return ResourceManager.GetString("offerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Offers&quot; is not valid..
        /// </summary>
        internal static string offers {
            get {
                return ResourceManager.GetString("offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Opening Hours&quot; is a valid number..
        /// </summary>
        internal static string openingHours {
            get {
                return ResourceManager.GetString("openingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Parents&quot; is not valid..
        /// </summary>
        internal static string parents {
            get {
                return ResourceManager.GetString("parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Part of Season&quot; is not valid..
        /// </summary>
        internal static string partOfSeason {
            get {
                return ResourceManager.GetString("partOfSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Part of TV Series&quot; is not valid..
        /// </summary>
        internal static string partOfTVSeries {
            get {
                return ResourceManager.GetString("partOfTVSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Payment Accepted&quot; is not valid..
        /// </summary>
        internal static string paymentAccepted {
            get {
                return ResourceManager.GetString("paymentAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Performer in&quot; is not valid..
        /// </summary>
        internal static string performerIn {
            get {
                return ResourceManager.GetString("performerIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Performers&quot; is not valid..
        /// </summary>
        internal static string performers {
            get {
                return ResourceManager.GetString("performers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Photos&quot; is not valid..
        /// </summary>
        internal static string photos {
            get {
                return ResourceManager.GetString("photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Player Type&quot; is not valid..
        /// </summary>
        internal static string playerType {
            get {
                return ResourceManager.GetString("playerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Polygon&quot; is not valid..
        /// </summary>
        internal static string polygon {
            get {
                return ResourceManager.GetString("polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Postal Code&quot; is not valid..
        /// </summary>
        internal static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Post Office Box Number&quot; is not valid..
        /// </summary>
        internal static string postOfficeBoxNumber {
            get {
                return ResourceManager.GetString("postOfficeBoxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Prep Time&quot; is a valid number..
        /// </summary>
        internal static string prepTime {
            get {
                return ResourceManager.GetString("prepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Price&quot; is not an alphanumeric value..
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Price Currency&quot; is not valid..
        /// </summary>
        internal static string priceCurrency {
            get {
                return ResourceManager.GetString("priceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Price Range&quot; is not valid..
        /// </summary>
        internal static string priceRange {
            get {
                return ResourceManager.GetString("priceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Price Valid Until&quot; is a valid date..
        /// </summary>
        internal static string priceValidUntil {
            get {
                return ResourceManager.GetString("priceValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Primary Image of Page&quot; is not valid..
        /// </summary>
        internal static string primaryImageOfPage {
            get {
                return ResourceManager.GetString("primaryImageOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Print Column&quot; is not valid..
        /// </summary>
        internal static string printColumn {
            get {
                return ResourceManager.GetString("printColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Print Edition&quot; is not valid..
        /// </summary>
        internal static string printEdition {
            get {
                return ResourceManager.GetString("printEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Print Page&quot; is not valid..
        /// </summary>
        internal static string printPage {
            get {
                return ResourceManager.GetString("printPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Print Section&quot; is not valid..
        /// </summary>
        internal static string printSection {
            get {
                return ResourceManager.GetString("printSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Producer&quot; is not valid..
        /// </summary>
        internal static string producer {
            get {
                return ResourceManager.GetString("producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Product ID&quot; is not valid..
        /// </summary>
        internal static string productID {
            get {
                return ResourceManager.GetString("productID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Production Company&quot; is not valid..
        /// </summary>
        internal static string productionCompany {
            get {
                return ResourceManager.GetString("productionCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Protein Content&quot; is not valid..
        /// </summary>
        internal static string proteinContent {
            get {
                return ResourceManager.GetString("proteinContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Provider&quot; is not valid..
        /// </summary>
        internal static string provider {
            get {
                return ResourceManager.GetString("provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Publisher&quot; is not valid..
        /// </summary>
        internal static string publisher {
            get {
                return ResourceManager.GetString("publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Publishing Principles&quot; is not a valid URL..
        /// </summary>
        internal static string publishingPrinciples {
            get {
                return ResourceManager.GetString("publishingPrinciples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Qualifications&quot; is not valid..
        /// </summary>
        internal static string qualifications {
            get {
                return ResourceManager.GetString("qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that &quot;Rating Count&quot; is a valid number..
        /// </summary>
        internal static string ratingCount {
            get {
                return ResourceManager.GetString("ratingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Rating Value&quot; is not valid..
        /// </summary>
        internal static string ratingValue {
            get {
                return ResourceManager.GetString("ratingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Recipe Category&quot; is not valid..
        /// </summary>
        internal static string recipeCategory {
            get {
                return ResourceManager.GetString("recipeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Recipe Cuisine&quot; is not valid..
        /// </summary>
        internal static string recipeCuisine {
            get {
                return ResourceManager.GetString("recipeCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Recipe Instructions&quot; is not valid..
        /// </summary>
        internal static string recipeInstructions {
            get {
                return ResourceManager.GetString("recipeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Recipe Yield&quot; is not valid..
        /// </summary>
        internal static string recipeYield {
            get {
                return ResourceManager.GetString("recipeYield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Regions Allowed&quot; is not valid..
        /// </summary>
        internal static string regionsAllowed {
            get {
                return ResourceManager.GetString("regionsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Related to&quot; is not valid..
        /// </summary>
        internal static string relatedTo {
            get {
                return ResourceManager.GetString("relatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Reply to Url&quot; is not a valid URL..
        /// </summary>
        internal static string replyToUrl {
            get {
                return ResourceManager.GetString("replyToUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Representative of Page&quot; can only have one of the values, true or false..
        /// </summary>
        internal static string representativeOfPage {
            get {
                return ResourceManager.GetString("representativeOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Requires Subscription&quot; can only have one of the values, true or false..
        /// </summary>
        internal static string requiresSubscription {
            get {
                return ResourceManager.GetString("requiresSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Responsibilities&quot; is not valid..
        /// </summary>
        internal static string responsibilities {
            get {
                return ResourceManager.GetString("responsibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Review Body&quot; is not valid..
        /// </summary>
        internal static string reviewBody {
            get {
                return ResourceManager.GetString("reviewBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that &quot;Review Count&quot; is a valid number..
        /// </summary>
        internal static string reviewCount {
            get {
                return ResourceManager.GetString("reviewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Review Rating&quot; is a valid integer..
        /// </summary>
        internal static string reviewRating {
            get {
                return ResourceManager.GetString("reviewRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Reviews&quot; is not valid..
        /// </summary>
        internal static string reviews {
            get {
                return ResourceManager.GetString("reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Salary Currency&quot; is not valid..
        /// </summary>
        internal static string salaryCurrency {
            get {
                return ResourceManager.GetString("salaryCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Saturated Fat Content&quot; is not valid..
        /// </summary>
        internal static string saturatedFatContent {
            get {
                return ResourceManager.GetString("saturatedFatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Season Number&quot; must be a valid integer..
        /// </summary>
        internal static string seasonNumber {
            get {
                return ResourceManager.GetString("seasonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Seasons&quot; is not valid..
        /// </summary>
        internal static string seasons {
            get {
                return ResourceManager.GetString("seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Seller&quot; is not valid..
        /// </summary>
        internal static string seller {
            get {
                return ResourceManager.GetString("seller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Serves Cuisine&quot; is not valid..
        /// </summary>
        internal static string servesCuisine {
            get {
                return ResourceManager.GetString("servesCuisine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Serving Size&quot; is not valid..
        /// </summary>
        internal static string servingSize {
            get {
                return ResourceManager.GetString("servingSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Siblings&quot; is not valid..
        /// </summary>
        internal static string siblings {
            get {
                return ResourceManager.GetString("siblings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Significant Links&quot; is not a valid URL..
        /// </summary>
        internal static string significantLinks {
            get {
                return ResourceManager.GetString("significantLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Skills&quot; is not valid..
        /// </summary>
        internal static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sodium Content&quot; is not valid..
        /// </summary>
        internal static string sodiumContent {
            get {
                return ResourceManager.GetString("sodiumContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Source Organization&quot; is not valid..
        /// </summary>
        internal static string sourceOrganization {
            get {
                return ResourceManager.GetString("sourceOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Special Commitments&quot; is not valid..
        /// </summary>
        internal static string specialCommitments {
            get {
                return ResourceManager.GetString("specialCommitments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Spouse&quot; is not valid..
        /// </summary>
        internal static string spouse {
            get {
                return ResourceManager.GetString("spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Start Date&quot; is a valid date..
        /// </summary>
        internal static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Street Address&quot; is not valid..
        /// </summary>
        internal static string streetAddress {
            get {
                return ResourceManager.GetString("streetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sub Events&quot; is not valid..
        /// </summary>
        internal static string subEvents {
            get {
                return ResourceManager.GetString("subEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Sugar Content&quot; is not valid..
        /// </summary>
        internal static string sugarContent {
            get {
                return ResourceManager.GetString("sugarContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Super Event&quot; is not valid..
        /// </summary>
        internal static string superEvent {
            get {
                return ResourceManager.GetString("superEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Telephone&quot; is not valid..
        /// </summary>
        internal static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Thumbnail&quot; is not valid..
        /// </summary>
        internal static string thumbnail {
            get {
                return ResourceManager.GetString("thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Thumbnail Url&quot; is not a valid URL..
        /// </summary>
        internal static string thumbnailUrl {
            get {
                return ResourceManager.GetString("thumbnailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Ticker Symbol&quot; is not valid..
        /// </summary>
        internal static string tickerSymbol {
            get {
                return ResourceManager.GetString("tickerSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Title&quot; is not valid..
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Total Time&quot; is a valid number..
        /// </summary>
        internal static string totalTime {
            get {
                return ResourceManager.GetString("totalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Tracks&quot; is not valid..
        /// </summary>
        internal static string tracks {
            get {
                return ResourceManager.GetString("tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Trailer&quot; is not valid..
        /// </summary>
        internal static string trailer {
            get {
                return ResourceManager.GetString("trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Transcript&quot; is not valid..
        /// </summary>
        internal static string transcript {
            get {
                return ResourceManager.GetString("transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Trans Fat Content&quot; is not valid..
        /// </summary>
        internal static string transFatContent {
            get {
                return ResourceManager.GetString("transFatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Unsaturated Fat Content&quot; is not valid..
        /// </summary>
        internal static string unsaturatedFatContent {
            get {
                return ResourceManager.GetString("unsaturatedFatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that &quot;Upload Date&quot; is a valid date..
        /// </summary>
        internal static string uploadDate {
            get {
                return ResourceManager.GetString("uploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;URL&quot; is not a valid URL..
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that &quot;Version&quot; is a valid number..
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Video&quot; is not valid..
        /// </summary>
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Video Frame Size&quot; is not valid..
        /// </summary>
        internal static string videoFrameSize {
            get {
                return ResourceManager.GetString("videoFrameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Video Quality&quot; is not valid..
        /// </summary>
        internal static string videoQuality {
            get {
                return ResourceManager.GetString("videoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Width&quot; is not valid..
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Word Count&quot; must be a valid integer..
        /// </summary>
        internal static string wordCount {
            get {
                return ResourceManager.GetString("wordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Work Hours&quot; is not valid..
        /// </summary>
        internal static string workHours {
            get {
                return ResourceManager.GetString("workHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Work Location&quot; is not valid..
        /// </summary>
        internal static string workLocation {
            get {
                return ResourceManager.GetString("workLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Works for&quot; is not valid..
        /// </summary>
        internal static string worksFor {
            get {
                return ResourceManager.GetString("worksFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Worst Rating&quot; is not an alphanumeric value..
        /// </summary>
        internal static string worstRating {
            get {
                return ResourceManager.GetString("worstRating", resourceCulture);
            }
        }
    }
}
